package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// UserType represents a row from 'user_types'.
type UserType struct {
	ID          string `json:"id" db:"id" form:"id"`                            // id
	TypeName    string `json:"type_name" db:"type_name" form:"type_name"`       // type_name
	Description string `json:"description" db:"description" form:"description"` // description
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [UserType] exists in the database.
func (ut *UserType) Exists() bool {
	return ut._exists
}

// Deleted returns true when the [UserType] has been marked for deletion
// from the database.
func (ut *UserType) Deleted() bool {
	return ut._deleted
}

// Insert inserts the [UserType] to the database.
func (ut *UserType) Insert(ctx context.Context, db DB) error {
	switch {
	case ut._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case ut._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO user_types (` +
		`id, type_name, description` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`
	// run
	logf(sqlstr, ut.ID, ut.TypeName, ut.Description)
	if _, err := db.ExecContext(ctx, sqlstr, ut.ID, ut.TypeName, ut.Description); err != nil {
		return logerror(err)
	}
	// set exists
	ut._exists = true
	return nil
}

// Update updates a [UserType] in the database.
func (ut *UserType) Update(ctx context.Context, db DB) error {
	switch {
	case !ut._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case ut._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE user_types SET ` +
		`type_name = $1, description = $2 ` +
		`WHERE id = $3`
	// run
	logf(sqlstr, ut.TypeName, ut.Description, ut.ID)
	if _, err := db.ExecContext(ctx, sqlstr, ut.TypeName, ut.Description, ut.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [UserType] to the database.
func (ut *UserType) Save(ctx context.Context, db DB) error {
	if ut.Exists() {
		return ut.Update(ctx, db)
	}
	return ut.Insert(ctx, db)
}

// Upsert performs an upsert for [UserType].
func (ut *UserType) Upsert(ctx context.Context, db DB) error {
	switch {
	case ut._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO user_types (` +
		`id, type_name, description` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`type_name = EXCLUDED.type_name, description = EXCLUDED.description `
	// run
	logf(sqlstr, ut.ID, ut.TypeName, ut.Description)
	if _, err := db.ExecContext(ctx, sqlstr, ut.ID, ut.TypeName, ut.Description); err != nil {
		return logerror(err)
	}
	// set exists
	ut._exists = true
	return nil
}

// Delete deletes the [UserType] from the database.
func (ut *UserType) Delete(ctx context.Context, db DB) error {
	switch {
	case !ut._exists: // doesn't exist
		return nil
	case ut._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM user_types ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, ut.ID)
	if _, err := db.ExecContext(ctx, sqlstr, ut.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	ut._deleted = true
	return nil
}

// UserTypeByID retrieves a row from 'user_types' as a [UserType].
//
// Generated from index 'sqlite_autoindex_user_types_1'.
func UserTypeByID(ctx context.Context, db DB, id string) (*UserType, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, type_name, description ` +
		`FROM user_types ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	ut := UserType{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&ut.ID, &ut.TypeName, &ut.Description); err != nil {
		return nil, logerror(err)
	}
	return &ut, nil
}
