// Code generated by goclt. DO NOT EDIT.
package types{{if .ContainsTime}}
import (
	"time"
){{end}}
{{.Types}}
{{if .HasConsts}}
// define the socket topics
const (
	{{range $k, $v := .Consts}}{{$k}} = "{{$v}}"
	{{end}})
{{end}}
