name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run go mod tidy
        run: go mod tidy

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.1"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Makefile commands
        run: make templ-fmt && make templ

      - name: Build with Vite
        run: pnpm run build

      - name: Deploy
        run: echo "Add your deployment steps here"
